language: node_js
env:
  - CXX=g++-4.8
node_js:
- '8'
addons:
  ssh_known_hosts: dev.coach.plus
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_install:
- openssl aes-256-cbc -K $encrypted_91fb1ba2c124_key -iv $encrypted_91fb1ba2c124_iv
  -in deploy_coach-plus.enc -out /tmp/deploy_coach-plus -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_coach-plus
- ssh-add /tmp/deploy_coach-plus
install:
- npm install -g pm2
- cd server && npm install
script:
- npm run test
deploy:
- provider: script
  skip_cleanup: true
  script: cd ../ && pm2 deploy ecosystem.json staging
  on:
    branch: master