# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildNumber)'
steps:
- task: Docker@2
  displayName: Login to Docker Hub
  inputs:
    command: login
    containerRegistry: DockerHub
- script: |
    export imageName="mathandoro/coach-plus-server"
    docker build -t $imageName:$(tag) -t $imageName:latest .
    docker push $imageName:$(tag)
    docker push $imageName:latest
  displayName: 'build & publish docker image'
- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'deployment'
    targetPath: './deploy'